---
- name: Install SELinux python bindings
  yum:
    name: libselinux-python
    state: present

- name: Copy hosts file
  copy:
    src: hosts
    dest: /etc/hosts

- name: Copy resolv.conf file
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
